# Generated by Django 4.1.7 on 2023-04-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='question_tags', to='questions.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/images/avatars', verbose_name='Avatar'),
        ),
    ]
