# Generated by Django 4.1.7 on 2023-07-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='url',
            new_name='slug',
        ),
    ]
