# Generated by Django 4.1.7 on 2023-04-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_tags_alter_question_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='questionimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='questions_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
