# Generated by Django 4.2 on 2023-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_rename_answer_answervote_obj_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerimages",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="answers_images/%Y/%m/%d/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="questionimages",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="questions_images/%Y/%m/%d/",
                verbose_name="Картинка",
            ),
        ),
    ]
