# Generated by Django 4.1.7 on 2023-07-18 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-likes', 'date_published'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='questions_a_likes_3c6344_idx',
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-likes', 'date_published'], name='questions_a_likes_d172ea_idx'),
        ),
    ]
