# Generated by Django 4.1.7 on 2023-04-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_category_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.SlugField(default=models.CharField(max_length=20, unique=True, verbose_name='Tag'), max_length=160, unique=True),
        ),
    ]
