# Generated by Django 4.2 on 2023-08-28 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0006_alter_answerimages_image_alter_questionimages_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answervote",
            old_name="obj",
            new_name="vote_target",
        ),
        migrations.RenameField(
            model_name="questionvote",
            old_name="obj",
            new_name="vote_target",
        ),
    ]
