# Generated by Django 4.1.7 on 2023-07-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_questionimages_options_answer_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
