# Generated by Django 4.1.7 on 2023-07-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_answer_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/', verbose_name='Картинка'),
        ),
    ]
