# Generated by Django 4.1.7 on 2023-07-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_answerimages_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['likes', '-date_published'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='questions_a_likes_d172ea_idx',
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['likes', '-date_published'], name='questions_a_likes_8eba13_idx'),
        ),
    ]
