version: '3.8'

services:
  web-app:
    build:
      context: .
    container_name: "web-app"
    command: python -m uvicorn ask_project.asgi:application --host 0.0.0.0 --port 8000 --workers 4
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - database
      - redis

  database:
    image: postgres:15.4-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.1-alpine
    container_name: "ask_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  celery:
    image: celery
    build:
      context: .
    container_name: "celery"
    command: celery --app=ask_project worker -l info -B
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND_BACKEND=redis://redis:6379/0
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - redis
      - database

  flower:
    image: mher/flower
    container_name: "flower"
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  pg_data:
  redis_data:
