version: '3'

services:
  web-app:
    build:
      context: .
    container_name: "ask_web"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - database
      - redis

  database:
    image: postgres:15.4-alpine
    container_name: "ask_database"
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.1-alpine
    container_name: "ask_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
