# Generated by Django 4.2 on 2023-08-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_read_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Прочитано"
            ),
        ),
    ]
