# Generated by Django 4.2 on 2023-08-30 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0005_remove_notification_read_at_notification_is_read_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="AlertNotification",
        ),
    ]
