# Generated by Django 4.2 on 2023-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notification_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
    ]
