# Generated by Django 4.2.5 on 2023-09-26 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_notification_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
    ]
