# Generated by Django 4.2.5 on 2024-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/%Y/%m/%d/"
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("city", models.CharField(blank=True, max_length=25)),
                ("country", models.CharField(blank=True, max_length=25)),
                ("status", models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
