# Generated by Django 4.2 on 2023-08-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(blank=True, max_length=250, verbose_name="Статус"),
        ),
    ]
