# Generated by Django 4.2 on 2023-08-30 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0002_remove_vote_voted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="voted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
    ]
