# Generated by Django 4.2.5 on 2024-01-07 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0002_rename_vote_vote_vote_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="vote_type",
            new_name="vote",
        ),
    ]
