# Generated by Django 4.2 on 2023-08-30 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0003_vote_voted_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="voted_at",
            new_name="timestamp",
        ),
    ]
