# Generated by Django 4.2.5 on 2024-01-26 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
